FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

WORKDIR /app

COPY CodeEditorApi/ .

RUN dotnet publish CodeEditorApi -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 80
ARG ASPNETCORE_ENVIRONMENT
ENV ASPNETCORE_ENVIRONMENT $ASPNETCORE_ENVIRONMENT
ENTRYPOINT ["dotnet", "CodeEditorApi.dll"]
